global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: "production"

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: "nodejs"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "paint-project-01"
      - source_labels: [__meta_environment]
        target_label: environment

  - job_name: "nodejs-process"
    static_configs:
      - targets: ["host.docker.internal:9100"] # Jika menggunakan node-exporter

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
